grpo_config:
  batch_size: 8
  checkpoint_interval: 100
  clip_eps: 0.2
  clip_grad_norm: 0.0
  entropy_loss_coef: 0.0
  eval_batch_size: 64
  eval_interval: 50
  gamma: 1.0
  gradient_accumulate_steps: 16
  group_size: 16
  kl_loss_coef: 0.0
  max_new_tokens: 900
  max_prompt_length: 512
  max_steps: 2000
  normalize_advantages: true
  normalize_group_rewards: true
  num_updates: 1
  repetition_penalty: 1.0
  rollout_size: 512
  sync_reference_interval: 0
  temperature: 1.0
  top_k: 0
  top_p: 0.95
  xml_format: false
job:
  artifacts_path: ./runs/test_grpo_qwen2.5_1.5b_gsm8k
  datasets:
  - gsm
  max_test_samples: 1024
  seed: 117
model:
  flash_attention: true
  gradient_checkpointing: true
  load_in_4bit: false
  model_max_length: 4000
  pretrained_model: Qwen/Qwen2.5-1.5B
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 1.0e-06
    weight_decay: 0.0
  type: AdamW8bit
