"""Implements base RL trainer"""

import datetime
import os
from abc import ABC, abstractmethod
from contextlib import contextmanager
from copy import deepcopy
from typing import Any, Dict, Generator, List, Optional, Tuple, Union

import deepspeed
import numpy as np
import torch
from deepspeed import DeepSpeedEngine
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
from transformers import PreTrainedModel, PreTrainedTokenizer

from rl4llm.constants import EVAL_PHASE, LOGGING_PHASES, TRAIN_PHASE
from rl4llm.core.data_types import RLConfig
from rl4llm.core.distributed import DistributedManager
from rl4llm.core.training_mixin import TrainingMixin
from rl4llm.envs import EpisodeData, LLMEnv
from rl4llm.logging import LoggingManager


class RLTrainer(ABC, TrainingMixin):
    """
    Abstract base class for RL training with LLM in a distributed environment.
    Provides the core infrastructure and defines the interface for algorithm-specific components.
    """

    _train_phase: str = TRAIN_PHASE
    _eval_phase: str = EVAL_PHASE
    _log_phases: List[str] = LOGGING_PHASES

    def __init__(
        self,
        config: RLConfig,
        tokenizer: PreTrainedTokenizer,
        policy_engine: DeepSpeedEngine,
        dist_manager: DistributedManager,
        logger: LoggingManager,
        artifacts_path: str,
        train_env: LLMEnv,
        eval_env: Optional[LLMEnv] = None,
        seed: Optional[int] = 175,
    ):
        if policy_engine.zero_optimization_stage() == 3:
            logger.warning('Zero-3 is not fully supported')

        if config.train_rollout_size % dist_manager.world_size != 0:
            raise ValueError(
                f"Rollout size must be divisible by {dist_manager.world_size}"
            )

        self.config = config
        self.tokenizer = tokenizer
        self.policy_engine = policy_engine
        self.dist_manager = dist_manager
        self.logger = logger
        self.train_env = train_env
        self.eval_env = eval_env
        self.artifacts_path = artifacts_path
        self.seed = seed

        self.device = self.dist_manager.device
        self.torch_dtype = self._get_torch_dtype()

        # Setup directories
        self.checkpoint_dir = os.path.join(self.artifacts_path, 'checkpoints')
        if self.dist_manager.is_master:
            os.makedirs(self.checkpoint_dir, exist_ok=True)
        self.dist_manager.barrier()  # Ensure dirs exist before proceeding

        # Reference model (optional, common in PPO-like methods)
        self.reference_model: Optional[PreTrainedModel] = (
            self._create_reference_model()
            if self.config.kl_loss_coef > 0
            else None
        )

        # Internal state
        self.global_step = 0
        self.policy_update_count = 0  # Tracks optimizer steps
        self.ref_update_count = 0

        self.initialize_trainer()
        self.logger.info('RL Trainer initialized.')

    @abstractmethod
    def initialize_trainer(self):
        """Any algorithm specific initialization  here"""

    @abstractmethod
    def generate_experience(self) -> List[Any]:
        """
        Generates experience (e.g., rollouts, trajectories) using the current policy.
        This is algorithm-specific (e.g., PPO needs states, actions, logprobs, rewards, values).
        Should handle interaction with the environment/LLM feedback.
        Returns:
            List[Any]: A list of collected experience elements (e.g., trajectories)
                       specific to the current rank.
        """
        pass

    @abstractmethod
    def compute_loss(
        self, experience_batch: Any, **kwargs
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """
        Computes the loss for a batch of experience.
        Args:
            experience_batch: A batch collated from the generated experience.
        Returns:
            Tuple[torch.Tensor, Dict[str, float]]: The computed loss tensor and a dictionary
                                                   of metrics for logging.
        """
        pass

    @abstractmethod
    def build_train_loader(self, experience: List[Any]) -> DataLoader:
        """
        Processes the generated experience and creates a DataLoader for training updates.
        Args:
            experience: The list of experience elements generated by `generate_experience`.
        Returns:
            DataLoader: DataLoader yielding batches ready for `compute_loss`.
        """
        pass

    @abstractmethod
    @torch.inference_mode()
    def evaluate_step(self) -> None:
        """
        Performs evaluation using the current policy model.
        """
        pass

    @abstractmethod
    def train_step(self, train_dataloader: DataLoader) -> None:
        """
        Performs the policy update using collected rollout.
        """
        pass

    @abstractmethod
    def sync_policy_model(self):
        """Sync policy model weights between actor and learner"""

    @contextmanager
    def unwrapped_model_for_generation(
        self,
    ) -> Generator[PreTrainedModel, None, None]:
        """Gets the true HF model from the deepspeed engine for generation"""

        if self.is_zero3_enabled():
            with deepspeed.zero.GatheredParameters(
                self.policy_engine.parameters()
            ):
                yield self.policy_engine.module

        yield self.policy_engine.module

        self.clean_up()

    def _prepare_for_generation(self):
        """Sets models to evaluation mode for experience generation."""
        self.policy_engine.eval()
        if self.reference_model:
            self.reference_model = self.reference_model.to(self.device)
            self.reference_model.eval()
        self.clean_up()

    def _prepare_for_training(self):
        """Sets models back to training mode."""
        self.policy_engine.train()
        # Move reference model back to GPU if moved earlier and needed
        if self.reference_model and self.reference_model.device != self.device:
            self.reference_model = self.reference_model.to('cpu')
        self.clean_up()

    def _sync_reference_model(self):
        """Updates the reference model weights with the current policy model weights."""
        if not self.reference_model:
            return

        self.logger.info('Syncing reference model...')
        with self.unwrapped_model_for_generation() as model:
            state_dict = model.state_dict()
            self.reference_model.load_state_dict(state_dict)
            self.ref_update_count += 1
            self.logger.info('Reference model synced.')

        self.clean_up()

    def _create_reference_model(self) -> Optional[PreTrainedModel]:
        """Creates a non-trainable copy of the policy model."""
        self.logger.info('Creating reference model...')
        # TODO maybe create reference model with deepspeed??
        with self.unwrapped_model_for_generation() as model:
            ref_model = deepcopy(model)
            ref_model.eval()
            for param in ref_model.parameters():
                param.requires_grad = False
        self.logger.info('Reference model created.')
        return ref_model

    def _get_torch_dtype(self) -> torch.dtype:
        """Get torch type from the engine config"""
        if self.policy_engine.bfloat16_enabled():
            return torch.bfloat16
        elif torch.cuda.is_available() and torch.cuda.is_bf16_supported():
            return torch.float16
        return torch.float32

    def is_zero3_enabled(self) -> bool:
        """Returns true if Zero-3 is enabled"""
        return self.policy_engine.zero_optimization_stage() == 3

    def log_batch_episodes(
        self,
        phase: str,
        samples: List[EpisodeData],
        step: int,
    ) -> None:
        """Log batch samples to Tensorboard and external files"""

        if phase not in self._log_phases:
            raise ValueError(
                f"Invalid phase {phase}, expect to be [{self._log_phases}]"
            )

        metric_key = f"objective/{phase}"
        token_metric_key = f"tokens/{phase}"
        for ep in samples:
            data_to_log = {
                'rank': self.dist_manager.global_rank,
                'prompt_text': ep.prompt_text,
                'prompt_length': ep.prompt_length,
                'completion_length': ep.completion_length,
                'completion_text': ep.completion_text,
                'timestamp': ep.timestamp,
                **ep.reward_dict,
            }

            if ep.raw_data is not None and 'ground_truth' in ep.raw_data:
                data_to_log['ground_truth'] = ep.raw_data['ground_truth']

            self.logger.log_sample(phase, data_to_log, step)
            for k, v in ep.reward_dict.items():
                self.logger.log_scalar(f"{metric_key}/{k}", v)
            # Token usage
            self.logger.log_scalar(
                f"{token_metric_key}/completion_length", ep.completion_length
            )
            self.logger.log_scalar(
                f"{token_metric_key}/prompt_length", ep.prompt_length
            )

    def save_checkpoint(self, step: int):
        """Saves model checkpoint using DeepSpeed."""
        tag = f"iteration_{step}"
        save_path = os.path.join(self.checkpoint_dir, tag)
        self.logger.info(f"Saving checkpoint to {save_path}...")
        # DeepSpeed handles distributed saving internally
        self.policy_engine.save_checkpoint(save_path)
        self.dist_manager.barrier()
        self.logger.info('Checkpoint saved.')

    def train(self, job_config: Dict):
        """Main training loop."""
        self.logger.info('Starting training...')
        if job_config and self.dist_manager.is_master:
            self.logger.log_hyperparams(job_config)

        self.dist_manager.synchronize()

        # Initial evaluation before training starts
        if self.config.eval_interval > 0 and self.eval_env:
            self.logger.info('Running initial evaluation...')
            with self.logger.timer('evaluate'):
                self._prepare_for_generation()
                self.evaluate_step()
                self.clean_up()
            self.dist_manager.barrier()

        for t in range(self.config.max_steps):
            with self.logger.timer('global_step'):
                self.global_step = t
                # 1. Generation Phase
                with self.logger.timer('generation'):
                    self._prepare_for_generation()
                    # generate_experience returns rank-local experience
                    local_experience = self.generate_experience()
                    self.clean_up()
                self.dist_manager.barrier()

                # 2. Learning Phase
                with self.logger.timer('train'):
                    self._prepare_for_training()
                    # processes local_experience and returns a DataLoader
                    train_dataloader = self.build_train_loader(local_experience)
                    self.train_step(train_dataloader)
                    self.clean_up()
                self.dist_manager.barrier()

                # 3. Post-Iteration Operations
                # Sync policy model
                with self.logger.timer('sync_policy_model'):
                    self.sync_policy_model()
                self.dist_manager.barrier()

                # Sync reference model
                if (
                    self.reference_model
                    and self.config.sync_reference_interval > 0
                    and (t + 1) % self.config.sync_reference_interval == 0
                ):
                    with self.logger.timer('_sync_reference_model'):
                        self._sync_reference_model()
                    self.dist_manager.barrier()

                # Checkpointing
                if (
                    self.config.checkpoint_interval > 0
                    and (t + 1) % self.config.checkpoint_interval == 0
                ):
                    with self.logger.timer('checkpoint'):
                        self.save_checkpoint(t + 1)

                # Evaluation
                if (
                    self.config.eval_interval > 0
                    and self.eval_env
                    and (t + 1) % self.config.eval_interval == 0
                ):
                    with self.logger.timer('evaluate'):
                        self._prepare_for_generation()
                        self.evaluate_step()
                        self.clean_up()
                    self.dist_manager.barrier()

            # Logging metrics
            self.logger.aggregate_and_log(self.global_step)

            # Clean up memory
            del local_experience
            del train_dataloader
            self.clean_up()

        self.logger.info('Training finished.')
        self.on_exit()

    def on_exit(self):
        """Handles exits like kill of process"""
        # Final checkpoint save
        self.save_checkpoint(self.config.max_steps)
        self.logger.close()
