# Top-level exclude applies to all hooks
exclude: |
  (?x)^(
      ^notebooks/|
      ^checkpoints/|
      ^testing/|
      ^.vscode/|
      .*\.(tex|sty|bib|csv|log|sgf|json|jsonl|txt|toml|yaml|model)
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
        exclude: ^(.vscode)
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=50000']
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-pyproject>=1.2.3' # Ensure load the config from pyproject.toml
        ]
        args: [
            '--toml-config=pyproject.toml'
        ]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  
