grpo_config:
  batch_size: 4
  checkpoint_interval: 100
  clip_eps: 0.2
  clip_grad_norm: 0.0
  eval_batch_size: 32
  eval_interval: 50
  gamma: 1.0
  gradient_accumulate_steps: 32
  group_size: 16
  group_temperature: true
  kl_loss_coef: 0.01
  max_new_tokens: 1300
  max_prompt_length: 500
  max_steps: 300
  normalize_advantages: false
  normalize_group_rewards: true
  num_updates: 1
  repetition_penalty: 1.0
  rollout_size: 512
  sync_reference_interval: 120
  system_prompt: "A conversation between User and Assistant. The user asks a question,\
    \ and the Assistant solves it.\nThe assistant first thinks about the reasoning\
    \ process in the mind and then provides the user with the answer. \nThe reasoning\
    \ process and answer are enclosed within <think> </think> and\n<answer> </answer>\
    \ tags, respectively, i.e., <think> reasoning process here </think>\n<answer>\
    \ answer here </answer>.\n"
  temperature: 0.99
  top_k: 0
  top_p: 0.95
  xml_format: true
job:
  artifacts_path: ./runs/group_grpo_qwen2.5_1.5b_gsm4k
  datasets:
  - gsm
  max_test_samples: 1024
  max_train_samples: 4096
  seed: 117
model:
  flash_attention: true
  gradient_checkpointing: true
  load_in_4bit: false
  pretrained_model: Qwen/Qwen2.5-1.5B-Instruct
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 1.0e-06
    weight_decay: 0.0
  type: AdamW8bit
