coherent_classification_model:
  checkpoint_path: models/coherent_classification_longformer
  gradient_checkpointing: true
  load_in_4bit: false
  model_max_length: 4000
  pretrained_model: allenai/longformer-base-4096
grpo_config:
  batch_size: 4
  checkpoint_interval: 100
  clip_eps: 0.2
  clip_grad_norm: 1.0
  entropy_loss_coef: 0.0
  eval_batch_size: 64
  eval_interval: 25
  explore_decay_steps: 100
  explore_init_epsilon: 0.5
  explore_max_replacements: 3
  explore_min_epsilon: 0.0
  explore_start_steps: 3
  explore_top_k: 50
  gamma: 1.0
  gradient_accumulate_steps: 16
  group_size: 32
  group_temperature: true
  kl_loss_coef: 0.0
  max_new_tokens: 1000
  max_prompt_length: 500
  max_steps: 300
  max_temperature: 1.2
  min_temperature: 0.6
  normalize_advantages: false
  normalize_group_rewards: true
  num_updates: 1
  repetition_penalty: 1.0
  rollout_size: 1024
  sync_reference_interval: 0
  system_prompt: "A conversation between User and Assistant. The user asks a question,\
    \ and the Assistant solves it.  \nThe Assistant first thinks about the reasoning\
    \ process internally and then provides the user with the answer. \n"
  temperature: 0.7
  top_k: 0
  top_p: 0.95
  xml_format: false
job:
  artifacts_path: ./runs/explore_grpo_qwen2.5_1.5b_gsm8k
  datasets:
  - gsm
  max_test_samples: 1024
  seed: 117
model:
  flash_attention: true
  gradient_checkpointing: true
  load_in_4bit: false
  model_max_length: 4000
  pretrained_model: Qwen/Qwen2.5-1.5B-Instruct
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 5.0e-07
    weight_decay: 0.0
  type: AdamW8bit
