grpo_config:
  batch_size: 4
  checkpoint_interval: 100
  clip_eps: 0.2
  clip_grad_norm: 1.0
  eval_batch_size: 32
  eval_interval: 50
  explore_decay_steps: 200
  explore_init_epsilon: 0.9
  explore_min_epsilon: 0.1
  explore_noise: 0.25
  explore_start_ratio: 0.1
  explore_top_k: 100
  gamma: 1.0
  gradient_accumulate_steps: 16
  group_size: 16
  group_temperature: true
  kl_loss_coef: 0.01
  max_new_tokens: 1200
  max_prompt_length: 600
  max_steps: 500
  normalize_advantages: false
  normalize_group_rewards: true
  num_updates: 3
  rollout_size: 1024
  sync_reference_interval: 300
  system_prompt: 'Think about the reasoning process in your mind before give a final
    answer to the problem. Present your final answer within \\boxed{}.

    '
  temperature: 0.9
  xml_format: false
job:
  artifacts_path: ./runs/explore_grpo_qwen2.5_1.5b_gsm8k
  datasets:
  - gsm
  max_test_samples: 512
  max_train_samples: 8000
  seed: 117
model:
  flash_attention: true
  gradient_checkpointing: true
  load_in_4bit: false
  pretrained_model: Qwen/Qwen2.5-1.5B-Instruct
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 9.0e-07
    weight_decay: 0.0
  type: AdamW8bit
