# RL GRPO config
job:
  seed: 117
  artifacts_path: "./runs/group_grpo_qwen2.5_1.5b_gsm1k"
  datasets: # List of math datasets to load
    - "gsm"
    # - "math"
  max_train_samples: 1024         # for a quick run
  max_test_samples: 512        

model:
  pretrained_model: "Qwen/Qwen2.5-1.5B-Instruct"
  load_in_4bit: false
  gradient_checkpointing: true
  flash_attention: true

grpo_config:
  max_steps: 150
  rollout_size: 512
  num_updates: 1
  batch_size: 4
  gradient_accumulate_steps: 32
  # dynamic_discount: true            # compute dynamic discount based on completion length
  # min_gamma: 0.999                  # for compute dynamic discount
  # max_gamma: 0.9997                 # for compute dynamic discount
  # max_completion_length: 4000       # for compute dynamic discount
  gamma: 1.0                          # fixed discount
  clip_eps: 0.2                       # PPO policy clip parameter
  normalize_group_rewards: true       
  normalize_advantages: false
  kl_loss_coef: 0.01
  clip_grad_norm: 0.0
  sync_reference_interval: 100        # every N iteration

  # for sample generation
  max_prompt_length: 500              # skip sample question that's too long
  group_size: 16                      # for each sample we generate a group of answers
  xml_format: true                   # check for R1 style XML format
  system_prompt: |
    A conversation between User and Assistant. The user asks a question, and the Assistant solves it.
    The assistant first thinks about the reasoning process in the mind and then provides the user with the answer. 
    The reasoning process and answer are enclosed within <think> </think> and
    <answer> </answer> tags, respectively, i.e., <think> reasoning process here </think>
    <answer> answer here </answer>.
  max_new_tokens: 1500
  temperature: 0.9
  repetition_penalty: 1.0
  top_p: 0.95
  top_k: 50
  
  group_temperature: true           # group temperature where some are more 'exploitive'

  # evaluation
  eval_batch_size: 32
  eval_interval: 30

  # others
  checkpoint_interval: 100            # every N iteration

optimizer:
  type: AdamW8bit
  params:
    lr: 1.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.0

# scheduler:
#   type: "OneCycleLR"
#   params:
#     warmup_fraction: 0.02
#     initial_lr_fraction: 0.1
#     final_lr_fraction: 0.5
