# RL GRPO config
job:
  seed: 117
  artifacts_path: "./runs/test_explore_grpo_qwen2.5_0.5b_gsm8k"
  datasets: # List of math datasets to load
    - "gsm"
    # - "math"
  # max_train_samples: 4096         # for a quick run
  max_test_samples: 1024        

model:
  pretrained_model: "Qwen/Qwen2.5-0.5B"
  load_in_4bit: false
  gradient_checkpointing: true
  flash_attention: true
  model_max_length: 4000

grpo_config:
  max_steps: 100
  train_rollout_size: 512
  num_updates: 1
  train_micro_batch_size: 4
  train_batch_size: 64
  gamma: 1.0                          # fixed discount
  clip_eps: 0.2                       # PPO policy clip parameter
  normalize_group_rewards: true       
  normalize_advantages: false
  kl_loss_coef: 0.0
  entropy_loss_coef: 0.0
  # clip_grad_norm: 0.0
  sync_reference_interval: 0          # every N iteration

  # for sample generation
  max_prompt_tokens: 512              # skip sample question that's too long
  group_size: 16                      # for each sample we generate a group of answers
  max_completion_tokens: 1000
  temperature: 1.0                    # not used if using group_temperature
  repetition_penalty: 1.0
  top_p: 0.95
  top_k: 0

  # exploration generation
  group_temperature: true             # group temperature where we balance exploration and exploitation
  min_temperature: 0.0
  max_temperature: 1.0

  # control rate of explore
  explore_init_epsilon: 0.7           # exploration epsilon decay
  explore_min_epsilon: 0.0
  explore_decay_steps: 50

  # exploring start
  explore_steps: 2              # initial start steps to do random sampling
  explore_top_k: 30                   # Top K tokens to random sample during initial start steps

  # exploring by token replacement
  replace_prob: 0.5
  replace_threshold: 0.8
  replace_max_per_seq: 2         # max number of replacements to the same sequence

  # evaluation
  eval_rollout_size: 1024    
  eval_batch_size: 64
  eval_interval: 25

  # others
  checkpoint_interval: 100            # every N iteration


deepspeed_config:
  # memory_breakdown: true  # for debugging
  steps_per_print: 1000000 # disable default logging
  gradient_clipping: 0.0
  bf16:
    enabled: true
  optimizer:
    type: Adam
    params:
      lr: 1.0e-6                   
      betas: [0.9, 0.999]
      eps: 1.0e-8
      weight_decay: 0.0
      adam_w_mode: true
  # scheduler:
  #   type: "WarmupDecayLR"
  #   params:
  #     warmup_num_steps: 200
  #     total_num_steps: 10000
  #     warmup_min_lr: 1.0e-8
  #     warmup_max_lr: 9.0e-7
  zero_optimization:
    stage: 2
    contiguous_gradients: true
    overlap_comm: true
    allgather_partitions: true
    reduce_scatter: true
    # offload_param:
    #   device: cpu
    #   pin_memory: false
    # offload_optimizer:
    #   device: cpu
    #   pin_memory: false
  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: true
    number_checkpoints: null
    synchronize_checkpoint_boundary: false

