# Synthetic coherent dataset generation config
job:
  seed: 193
  artifacts_path: "./data/synthetic_coherent_dataset"
  datasets: # List of math datasets to load
    - "gsm"
    # - "math"
  max_train_samples: 32         # for a quick run
  max_test_samples: 4        
  n_samples_per_prompt: 4
  max_new_tokens: 512
  system_prompt: |
    A conversation between User and Assistant. The user asks a question, and the Assistant solves it.  
    The Assistant first thinks about the reasoning process internally and then provides the user with the answer.  
    The Assistant should prioritize **depth in reasoning** and **clarity in the final answer** while ensuring correctness.

    The reasoning process and answer are enclosed within `<think> </think>` and `<answer> </answer>` tags, respectively. i.e.,  
    `<think> Unstructured, free-form reasoning process exploring the problem in depth </think>`  
    `<answer> A clear and concise high-level summary of the solution and final answer </answer>`
  

model:
  pretrained_model: "Qwen/Qwen2.5-0.5B-Instruct"
  load_in_4bit: false
  gradient_checkpointing: false
  flash_attention: false
