# Synthetic coherent dataset generation config
job:
  seed: 193
  artifacts_path: "./data/synthetic_coherent_dataset/qwen2.5_7b_math1k"
  datasets: # List of math datasets to load
    # - "gsm"
    - "math"
  max_train_samples: 1000         # for a quick run
  max_test_samples: 100        
  n_samples: 8
  min_new_tokens: 250
  max_new_tokens: 3500
  system_prompt: |
    A conversation between User and Assistant. The user asks a question, and the Assistant solves it.  
    The Assistant first thinks about the reasoning process internally and then provides the user with the answer.  
    The Assistant should prioritize **depth in reasoning** and **clarity in the final answer** while ensuring correctness.

    The reasoning process and answer are enclosed within `<think> </think>` and `<answer> </answer>` tags, respectively. i.e.,  
    `<think> Unstructured, free-form reasoning process exploring the problem in depth </think>`  
    `<answer> A clear and concise high-level summary of the solution and final answer </answer>`
  
  # dual_language_system_prompts:
  #   - |
  #     **IMPORTANT RULE:** The assistant should first provide the reasoning process and answer the question in English and then translate the reasoning process and answer into Chinese.
  #   - |
  #     **IMPORTANT RULE:** The assistant should first provide the reasoning process and answer the question in English and then translate the reasoning process and answer into Japanese.

model:
  pretrained_model: "Qwen/Qwen2.5-7B-Instruct"
  load_in_4bit: false
  gradient_checkpointing: false
  flash_attention: true
