# Value model config
seed: 117

logging:
  output_dir: "./runs/test_run2_value_net_qwen2.5_0.5b_gsm8k"  # where to save all artifacts (tensorboard events, samples, checkpoints)
  enable_tensorboard: true
  sample_buffer_size: 100               # how often to save samples to external files
  sample_file_format: 'jsonl'           # external file type, support 'jsonl', 'jsonl.gz', 'parquet'
  log_level: 20

dataset: 
  names:                                # List of math datasets to load
    - "gsm"
    # - "math"
  # max_train_samples: 4096             # for a quick run
  # max_test_samples: 1024        

value_model:
  pretrained_model: "Qwen/Qwen2.5-0.5B"
  checkpoint_path: "./runs/test_value_net_qwen2.5_0.5b_gsm8k/checkpoints/epoch_0"    
  load_in_4bit: false
  gradient_checkpointing: true
  flash_attention: true
  model_max_length: 4000

value_net_config:
  train_rollout_size: 1024
  num_epochs: 5
  train_micro_batch_size: 8
  train_batch_size: 128
  gamma: 1.0                            # discount

  # for sample generation
  max_prompt_tokens: 512                # skip sample question that's too long
  group_size: 8                         # for each sample we generate a group of answers
  max_completion_tokens: 1000
  temperature: 0.9                      
  repetition_penalty: 1.0
  top_p: 0.95
  top_k: -1                             # -1 to disable

deepspeed:
  # memory_breakdown: true              # for debugging
  steps_per_print: 1000000              # disable default logging
  # train_micro_batch_size_per_gpu: 1      
  # train_batch_size: 1                    
  gradient_clipping: 0.0
  bf16:
    enabled: true
  optimizer:
    type: Adam
    params:
      lr: 1.0e-6                   
      betas: [0.9, 0.999]
      eps: 1.0e-8
      weight_decay: 0.0
  scheduler:
    type: "WarmupDecayLR"
    params:
      warmup_num_steps: 20
      total_num_steps: 1000
      warmup_min_lr: 1.0e-8
      warmup_max_lr: 1.0e-6
  zero_optimization:
    stage: 3
    contiguous_gradients: true
    overlap_comm: true
    allgather_partitions: true
    reduce_scatter: true
    # offload_param:
    #   device: cpu
    #   pin_memory: false
    # offload_optimizer:
    #   device: cpu
    #   pin_memory: false
  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: true
    number_checkpoints: null
    synchronize_checkpoint_boundary: false

