actor:
  decoding:
    do_sample: true
    max_new_tokens: 2048
    temperature: 0.6
    top_p: 1.0
datasets:
- math
deepspeed:
  activation_checkpointing:
    contiguous_memory_optimization: true
    cpu_checkpointing: true
    number_checkpoints: null
    partition_activations: true
    profile: false
    synchronize_checkpoint_boundary: false
  bf16:
    enabled: true
  gradient_clipping: 1.0
  optimizer:
    params:
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      lr: 1.0e-05
      weight_decay: 0.0
    type: Adam
  prescale_gradients: false
  scheduler:
    params:
      total_num_steps: 50000
      warmup_max_lr:
      - 1.0e-06
      - 1.0e-06
      - 9.0e-06
      warmup_min_lr:
      - 1.0e-07
      - 1.0e-07
      - 5.0e-06
      warmup_num_steps: 50
    type: WarmupDecayLR
  steps_per_print: 10000
  train_batch_size: 128
  train_micro_batch_size_per_gpu: 4
  wall_clock_breakdown: false
  zero_optimization:
    allgather_partitions: true
    contiguous_gradients: true
    memory_efficient_linear: false
    offload_optimizer:
      device: cpu
      pin_memory: true
    offload_param:
      device: cpu
    overlap_comm: true
    reduce_bucket_size: auto
    reduce_scatter: true
    stage: 2
    stage3_max_live_parameters: auto
    stage3_max_reuse_distance: auto
    stage3_param_persistence_threshold: auto
    stage3_prefetch_bucket_size: auto
    zero_hpz_partition_size: 8
    zero_quantized_gradients: false
    zero_quantized_weights: false
environment:
  max_reward: 1.0
  mid_step_score: 0.5
  min_reward: 0.0
  num_envs: 8
  shuffle: true
  state_config:
  - is_start: true
    should_grade: true
    state_id: reasoning
    system_prompt: 'Think first about the reasoning process in your mind and then
      provides the user

      with the answer. Please put your final answer (e.g. numerical value or expression)
      within \\boxed{}.

      '
    transitions:
    - prob: 1.0
      state_id: end_terminal
      terminal: true
    user_prompt: '{question}

      '
evaluator:
  decoding:
    do_sample: false
    max_new_tokens: 2048
    temperature: 0.0
    top_p: 1.0
  enabled: true
  interval: 10
  rollout_episodes: 500
job:
  artifacts_path: ./runs
  name: ppo_run_qwen2.5-3b
  seed: 117
logging:
  intervals:
    actor: 10
    evaluator: 10
    learner: 1
  level: INFO
model:
  activation_checkpoint: true
  initialize_value_weights: false
  load_checkpoint: ./checkpoints/sft/checkpoint_step_200
  load_in_4bit: false
  max_seq_len: 4096
  pretrained_model: Qwen/Qwen2.5-3B-Instruct
training_config:
  checkpoint_enabled: true
  checkpoint_interval: 200
  checkpoint_keep_n: 5
  gae_lambda: 0.95
  gamma: 1.0
  kl_coef: 0.01
  mix_kl_advantages: false
  normalize_advantages: true
  normalize_rewards: false
  num_epochs: 4
  policy_clip_eps: 0.2
  rollout_episodes: 512
  rollout_iterations: 10000
  value_clip_eps: 0.2
  value_loss_coef: 0.3
