config:
  batch_size: 16
  checkpoint_interval: 100
  clip_grad_norm: 1.0
  eval_batch_size: 32
  eval_interval: 100
  gradient_accumulate_steps: 8
  num_epochs: 2
job:
  artifacts_path: ./runs/coherent_classification_longformer
  dataset:
    test_path: data/coherent_dataset/test.parquet
    train_path: data/coherent_dataset/train.parquet
  max_test_samples: 4096
  max_train_samples: 50000
  seed: 117
model:
  gradient_checkpointing: true
  load_in_4bit: false
  model_max_length: 4000
  pretrained_model: allenai/longformer-base-4096
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 5.0e-06
    weight_decay: 0.0
  type: AdamW
scheduler:
  params:
    final_lr_fraction: 0.1
    initial_lr_fraction: 0.1
    warmup_fraction: 0.05
  type: OneCycleLR
