datasets:
- gsm
grpo_config:
  batch_size: 8
  checkpoint_interval: 100
  clip_eps: 0.2
  explore_decay_steps: 300
  explore_init_epsilon: 0.9
  explore_min_epsilon: 0.1
  explore_start_steps: 30
  explore_top_k: 50
  explore_top_k_beta: 0.5
  explore_uncertainty: 0.0
  gamma: 1.0
  gradient_accumulate_steps: 16
  group_size: 32
  group_temperature: true
  kl_loss_coef: 0.001
  max_new_tokens: 1024
  max_steps: 1000
  normalize_advantages: true
  normalize_group_rewards: true
  num_updates: 1
  rollout_size: 1024
  sync_reference_interval: 500
  system_prompt: 'Think about the reasoning process in your mind before give a final
    answer to the problem. Explore those "hmm", "aha" moments to reflect on your reasoning
    process. Present your final answer within \\boxed{}.

    '
  temperature: 0.9
  xml_format: false
job:
  artifacts_path: ./runs/grpo_qwen2.5_1.5b_2nd_run
  seed: 117
model:
  flash_attention: true
  gradient_checkpointing: true
  load_in_4bit: false
  pretrained_model: Qwen/Qwen2.5-1.5B-Instruct
optimizer:
  params:
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    lr: 1.0e-06
    weight_decay: 0.002
  type: AdamW8bit
scheduler:
  params:
    final_lr_fraction: 0.1
    initial_lr_fraction: 0.1
    warmup_fraction: 0.01
  type: OneCycleLR
