actor:
  decoding:
    do_sample: true
    max_new_tokens: 2048
    temperature: 0.6
    top_p: 1.0
datasets:
- math
deepspeed:
  bf16:
    enabled: true
  gradient_clipping: 1.0
  optimizer:
    params:
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      lr: 1.0e-05
      weight_decay: 0.0
    type: Adam
  prescale_gradients: false
  scheduler:
    params:
      total_num_steps: 50000
      warmup_max_lr:
      - 5.0e-06
      - 5.0e-06
      - 1.0e-05
      warmup_min_lr:
      - 1.0e-07
      - 1.0e-07
      - 1.0e-06
      warmup_num_steps: 100
    type: WarmupDecayLR
  steps_per_print: 10000
  train_batch_size: 120
  train_micro_batch_size_per_gpu: 4
  wall_clock_breakdown: false
  zero_optimization:
    allgather_bucket_size: 500000.0
    allgather_partitions: true
    contiguous_gradients: true
    overlap_comm: true
    reduce_bucket_size: 500000.0
    reduce_scatter: true
    stage: 2
environment:
  max_reward: 1.0
  mid_step_score: 0.5
  min_reward: 0.0
  num_envs: 8
  shuffle: true
  state_config:
  - is_start: true
    should_grade: true
    state_id: reasoning
    system_prompt: 'Think first about the reasoning process in your mind and then
      provides the user

      with the answer. Please put your final answer (e.g. numerical value or expression)
      within \\boxed{}.

      '
    transitions:
    - prob: 1.0
      state_id: end_terminal
      terminal: true
    user_prompt: '{question}

      '
evaluator:
  decoding:
    do_sample: false
    max_new_tokens: 2048
    temperature: 0.0
    top_p: 1.0
  enabled: true
  interval: 20
  rollout_episodes: 500
job:
  artifacts_path: ./runs
  name: ppo_run_qwen2.5-1.5b
  seed: 117
logging:
  intervals:
    actor: 10
    evaluator: 10
    learner: 1
  level: INFO
model:
  activation_checkpoint: true
  initialize_value_weights: false
  load_checkpoint: ./checkpoints/sft/checkpoint_step_100
  load_in_4bit: false
  max_seq_len: 4096
  pretrained_model: Qwen/Qwen2.5-1.5B-Instruct
training_config:
  checkpoint_enabled: true
  checkpoint_interval: 100
  checkpoint_keep_n: 5
  dynamic_discount: true
  gae_lambda: 0.95
  gamma: 1.0
  kl_loss_coef: 0.01
  max_expected_length: 10000
  max_gamma: 0.9995
  min_gamma: 0.9975
  normalize_advantages: true
  num_epochs: 4
  policy_clip_eps: 0.2
  rollout_episodes: 1024
  rollout_iterations: 10000
  value_clip_eps: 0.2
  value_loss_coef: 0.1
